name: Label issues
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Get Existing Labels
        id: get_labels
        run: |
          LABELS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                    -H "Accept: application/vnd.github.v3+json" \
                    https://api.github.com/repos/${{ github.repository }}/labels \
                    | jq -r '.[].name' | paste -sd "," -)
          echo "labels=$LABELS" >> $GITHUB_OUTPUT
      - name: Check for Keywords and Set Labels
        run: |
          IFS=',' 
          read -ra EXISTING_LABELS <<< "${{steps.get_labels.outputs.labels}}"
          ISSUE_NUMBER=${{ github.event.issue.number }}
          TITLE="${{ github.event.issue.title }}"
          for label in ${EXISTING_LABELS[@]}; do
              echo "$label"
              if grep -q "$label" <<< "$TITLE"; then
                  # Append label to LABELS variable
                  gh issue edit "$ISSUE_NUMBER" --add-label "$label"
              fi
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: triage
